namespace YCode.CLI;

[Inject]
internal sealed class ConfigManager
{
    private const string ConfigDirName = ".ycode";
    private const string ConfigFileName = "config.env";
    private static readonly string[] RequiredEnvVars = ["YCODE_AUTH_TOKEN", "YCODE_API_BASE_URI", "YCODE_MODEL"];

    private readonly string _configDir;
    private readonly string _configFile;
    private readonly Dictionary<string, string> _config;

    public ConfigManager()
    {
        var userProfile = Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);
        _configDir = Path.Combine(userProfile, ConfigDirName);
        _configFile = Path.Combine(_configDir, ConfigFileName);
        _config = [];

        LoadConfig();
    }

    private void LoadConfig()
    {
        if (!File.Exists(_configFile))
        {
            return;
        }

        var lines = File.ReadAllLines(_configFile);
        foreach (var line in lines)
        {
            var trimmed = line.Trim();
            if (string.IsNullOrEmpty(trimmed) || trimmed.StartsWith('#'))
            {
                continue;
            }

            // Remove 'export ' prefix if present
            var exportPrefix = "export ";
            if (trimmed.StartsWith(exportPrefix))
            {
                trimmed = trimmed[exportPrefix.Length..].Trim();
            }

            var parts = trimmed.Split('=', 2);
            if (parts.Length == 2)
            {
                var key = parts[0].Trim();
                var value = parts[1].Trim().Trim('"', '\'');

                if (!string.IsNullOrEmpty(key))
                {
                    _config[key] = value;
                }
            }
        }
    }

    private void SaveConfig()
    {
        if (!Directory.Exists(_configDir))
        {
            Directory.CreateDirectory(_configDir);
        }

        var lines = new List<string> { "# YCode Configuration File", "# Generated by YCode CLI", "" };

        foreach (var kvp in _config)
        {
            lines.Add($"export {kvp.Key}=\"{kvp.Value}\"");
        }

        File.WriteAllLines(_configFile, lines);
    }

    public string? GetEnvironmentVariable(string name)
    {
        // First check system environment
        var value = Environment.GetEnvironmentVariable(name);
        if (!string.IsNullOrEmpty(value))
        {
            return value;
        }

        // Fall back to config file
        return _config.TryGetValue(name, out var configValue) ? configValue : null;
    }

    public void EnsureConfiguration()
    {
        var missingVars = RequiredEnvVars
            .Where(envVar => string.IsNullOrEmpty(GetEnvironmentVariable(envVar)))
            .ToList();

        if (missingVars.Count == 0)
        {
            return;
        }

        Console.WriteLine();
        AnsiConsole.MarkupLine("[bold yellow]⚠ Configuration Required[/]");
        AnsiConsole.MarkupLine("[dim]The following environment variables are not set:[/]");

        foreach (var envVar in missingVars)
        {
            var description = envVar switch
            {
                "YCODE_AUTH_TOKEN" => "API authentication token",
                "YCODE_API_BASE_URI" => "API base endpoint URL",
                "YCODE_MODEL" => "Model identifier (e.g., gpt-4o)",
                _ => "Required configuration"
            };
            AnsiConsole.MarkupLine($"  [dim]•[/] [cyan]{envVar}[/] - {description}");
        }

        Console.WriteLine();
        AnsiConsole.MarkupLine("[dim]Please enter the required values. They will be saved to:[/]");
        AnsiConsole.MarkupLine($"  [cyan]{_configFile}[/]");
        Console.WriteLine();

        foreach (var envVar in missingVars)
        {
            var prompt = GetPromptForEnvVar(envVar);
            var defaultValue = GetDefaultValueForEnvVar(envVar);
            var input = ReadInput(prompt, defaultValue, !string.IsNullOrEmpty(defaultValue));

            if (!string.IsNullOrEmpty(input))
            {
                _config[envVar] = input!;
                Environment.SetEnvironmentVariable(envVar, input);
            }
        }

        SaveConfig();

        Console.WriteLine();
        AnsiConsole.MarkupLine("[bold green]✓ Configuration saved successfully[/]");
        Console.WriteLine();

        PrintSetupInstructions();
    }

    private static string GetPromptForEnvVar(string envVar)
    {
        return envVar switch
        {
            "YCODE_AUTH_TOKEN" => "Enter your API authentication token",
            "YCODE_API_BASE_URI" => "Enter your API base endpoint URL",
            "YCODE_MODEL" => "Enter the model identifier",
            _ => $"Enter value for {envVar}"
        };
    }

    private static string GetDefaultValueForEnvVar(string envVar)
    {
        return envVar switch
        {
            "YCODE_API_BASE_URI" => "https://api.openai.com/v1",
            "YCODE_MODEL" => "gpt-4o",
            _ => string.Empty
        };
    }

    private static string? ReadInput(string prompt, string? defaultValue = null, bool allowEmpty = false)
    {
        while (true)
        {
            var defaultPrompt = !string.IsNullOrEmpty(defaultValue)
                ? $"[dim]({defaultValue})[/] "
                : string.Empty;

            AnsiConsole.Markup($"[bold green]→[/] {prompt}: {defaultPrompt}");
            var input = Console.ReadLine();

            if (!string.IsNullOrEmpty(input))
            {
                return input;
            }

            if (!string.IsNullOrEmpty(defaultValue))
            {
                return defaultValue;
            }

            if (allowEmpty)
            {
                return null;
            }

            AnsiConsole.MarkupLine("[red]✗ This field cannot be empty. Please try again.[/]");
        }
    }

    private void PrintSetupInstructions()
    {
        var shellConfig = DetectShellConfigFile();

        if (!string.IsNullOrEmpty(shellConfig))
        {
            AnsiConsole.MarkupLine("[dim]To make these environment variables permanent, add this line to your shell configuration:[/]");
            Console.WriteLine();
            AnsiConsole.MarkupLine($"  [cyan]source \"{_configFile}\"[/]");
            Console.WriteLine();
            AnsiConsole.MarkupLine($"[dim]Your shell config file appears to be:[/] [cyan]{shellConfig}[/]");
        }
        else
        {
            AnsiConsole.MarkupLine("[dim]Note: To make these environment variables permanent across sessions,[/]");
            AnsiConsole.MarkupLine($"[dim]add this line to your shell configuration:[/] [cyan]source \"{_configFile}\"[/]");
        }
    }

    private static string? DetectShellConfigFile()
    {
        var userProfile = Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);

        // Check for common shell config files
        var shellFiles = new[]
        {
            Path.Combine(userProfile, ".zshrc"),
            Path.Combine(userProfile, ".bashrc"),
            Path.Combine(userProfile, ".bash_profile"),
            Path.Combine(userProfile, ".profile")
        };

        var shellEnv = Environment.GetEnvironmentVariable("SHELL");
        if (!string.IsNullOrEmpty(shellEnv))
        {
            var shellName = Path.GetFileName(shellEnv);
            var configFile = shellName switch
            {
                "zsh" => ".zshrc",
                "bash" => ".bashrc",
                _ => null
            };

            if (!string.IsNullOrEmpty(configFile))
            {
                var configPath = Path.Combine(userProfile, configFile);
                if (File.Exists(configPath))
                {
                    return configPath;
                }
            }
        }

        // Return first existing file
        return shellFiles.FirstOrDefault(File.Exists);
    }
}
